name: Manual workflow

on:
  workflow_dispatch:

jobs:

  clean:
    runs-on: ubuntu-latest

    steps:
    - name: install tree
      run: sudo apt -y update && sudo apt -y install tree
    - name: tree
      run: tree
